apiVersion: v1
kind: ConfigMap
metadata:
  name: cgi-config
  namespace: k8s-proj
data:
  app_name: "TEST LARAVEL K8S"
  app_key: "base64:77lw6aMFXq3qTBibgMKJo7W/cy1ueyDKjJTXoKqwOWk="
  app_debug: 'true'
  cgi_nginx_conf: |
    server {
      listen 80 default_server;
      root /app/public;
      index index.php index.html;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ .*\.php(\/.*)*$ {
        fastcgi_pass localhost:9000;
        include fastcgi.conf;

        # fastcgi_connect_timeout 300;
        # fastcgi_send_timeout 300;
        # fastcgi_read_timeout 300;
      }
    }

